-- MySQL Script generated by MySQL Workbench
-- ven. 12 mars 2021 17:39:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema webstart_automobile
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema webstart_automobile
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webstart_automobile` DEFAULT CHARACTER SET utf8 ;
USE `webstart_automobile` ;

-- -----------------------------------------------------
-- Table `webstart_automobile`.`brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webstart_automobile`.`brands` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webstart_automobile`.`cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webstart_automobile`.`cars` (
  `id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `model` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL,
  `brands_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_cars_brands_idx` (`brands_id` ASC) VISIBLE,
  CONSTRAINT `fk_cars_brands`
    FOREIGN KEY (`brands_id`)
    REFERENCES `webstart_automobile`.`brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webstart_automobile`.`pictures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webstart_automobile`.`pictures` (
  `id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `path` VARCHAR(255) NOT NULL,
  `created_at` VARCHAR(255) NOT NULL,
  `updated_at` VARCHAR(255) NOT NULL,
  `cars_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_pictures_cars1_idx` (`cars_id` ASC) VISIBLE,
  CONSTRAINT `fk_pictures_cars1`
    FOREIGN KEY (`cars_id`)
    REFERENCES `webstart_automobile`.`cars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
